#!/bin/bash

# The workaround script to overcome Firebase CLI's inability
# to fetch code outside of functions folder.

# This script should be run from project root like
# ./scripts/deploy-functions [project name]

set -x

# Step 1: Build All Projects

yarn install
yarn workspace github-query-core build
yarn workspace github-query-backend build
yarn workspace github-query-functions build:deploy

# Step 2: Setup mirror folders for deployments

mkdir temp
mkdir temp/functions

# Copy Code For Deployment
cp -R functions/build/ temp/functions/
rm -rf functions/build/
cp functions/functions-package.json temp/functions/package.json

# Copy package.json

echo '{}' >temp/firebase.json

cd temp
firebase deploy --only functions --project developer-sam
cd ../
rm -rf temp
