name: CI
on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Create Dummy Files
        run: echo "export default '${{ secrets.GITHUB_TOKEN }}';" > src/data/github-token.ts
      - name: Yarn Install
        run: yarn install
      - name: Prettier
        run: yarn format:check
      - name: Lint
        run: yarn lint
      - name: Type Check
        run: yarn build
      - name: Integration Test
        run: ./sam-repositories-analysis
