name: CI
on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Create Dummy Files
        run: ./create-dummy
      - name: Yarn Install
        run: yarn install
      - name: Prettier
        run: yarn prettier:check
      - name: Lint
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Create Dummy Files
        run: ./create-dummy
      - name: Yarn Install
        run: yarn install
      - name: Build backend
        run: yarn build:backend
      - name: Build frontend
        run: yarn build:frontend
