name: CI
on: [push]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Create Dummy Configuration Files
        run: |
          echo "export const GITHUB_TOKEN = '';" > src/backend/configuration.ts
          echo "export const DATABASE_URL = '';" >> src/backend/configuration.ts
          echo "{}" > src/backend/firebase-adminsdk.json
          echo "{}" > src/functions/fetch-configuration.json
      - name: Yarn Install
        run: yarn install
      - name: Prettier
        run: yarn prettier:check
      - name: Lint
        run: yarn lint
      - name: Build backend
        run: yarn build:backend
      - name: Build frontend
        run: yarn build:frontend
