name: CI
on: [push]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Create Dummy Configuration Files
        run: |
          echo "export const GITHUB_TOKEN = '';" > backend/configuration.ts
          echo "export const DATABASE_URL = '';" >> backend/configuration.ts
          echo "{}" > backend/firebase-adminsdk.json
          echo "{}" > functions/fetch-configuration.json
      - name: Yarn Install
        run: yarn install
      - name: Prettier
        run: yarn prettier:check
      - name: Build core
        run: yarn workspace github-query-core build
      - name: Build cli
        run: yarn workspace github-query-cli build
      - name: Build functions
        run: yarn workspace github-query-functions build
      - name: Build frontend
        run: yarn workspace github-query-frontend build
      - name: Lint
        run: yarn lint
